/* COGITATOR SERVICE RITE - cache-first machine spirit
 *
 * CR-Nanites-harness-0018 (high): the navigation fallback used to be
 *   .catch(() => caches.match('./index.html'))
 * on EVERY same-origin GET. An offline reload requested appcore.js, missed, and was
 *   answered with the HTML document under a text/html content type. The script failed to
 *   parse, `CogCore` stayed undefined, and the boot path threw: not degraded mode but a
 *   totally dead app with no message. Offline support was making the app STRICTLY WORSE
 *   than no offline support. The fallback is now scoped to navigations only, so a failed
 *   script request rejects and the browser surfaces an honest network error.
 *
 * CR-Nanites-harness-0007 (medium): `CACHE` was the hand-maintained literal
 *   'cogitator-v10' and nothing in the repo bumped it, so a shipped asset change stayed
 *   pinned in cache indefinitely. CACHE is now DERIVED from the precached assets'
 *   contents, and the digest below is GENERATED by tools/gen_sw_cache.py — so one bump
 *   invalidates the cache atomically instead of relying on a human remembering one line.
 */

/* The precached shell. `./appcore.js` was missing (CR-0018 part 1): index.html loads it
 * via <script src>, and it was reachable only through the runtime cache-write below,
 * which requires a prior successful ONLINE fetch — so the very first offline visit, the
 * case offline support exists for, could not get it at all.
 * The phase-21 suite asserts every same-origin <script src>/stylesheet in index.html is
 * in this list, so the next asset added to the page cannot be forgotten here. */
const SHELL = ['./index.html','./appcore.js','./manifest.webmanifest','./sw.js','./icon.svg','./icon.png','./icon-192.png','./WH40KIDLE.gif','./WH40KSpinAnimation.gif'];

/* ==== BEGIN GENERATED asset digests (tools/gen_sw_cache.py) ==== */
/* GENERATED by tools/gen_sw_cache.py from the real asset files -- do not edit by
   hand. `python3 tools/gen_sw_cache.py --check` fails if these do not match, and
   test_e2e.py runs that check. CR-Nanites-harness-0007: this map is what makes
   CACHE a derivation rather than a human-remembered literal. */
const ASSET_DIGESTS = {
  './index.html': '47360252333b2a8e',
  './appcore.js': 'dea77ef8dcf9e874',
  './manifest.webmanifest': '438b41770fc283e5',
  './sw.js': '' /* excluded: embeds this map */,
  './icon.svg': '77313c7599fb1a3b',
  './icon.png': 'e9376ae994ffcf37',
  './icon-192.png': 'e11e314680f41152',
  './WH40KIDLE.gif': '45a77d2fba6f618e',
  './WH40KSpinAnimation.gif': 'e2d2194c91f7f452',
};
/* ==== END GENERATED asset digests ==== */

/**
 * The cache name, derived from WHICH assets are precached and WHAT they contain.
 * Pure and deterministic: same shell + same contents -> same name; any change to either
 * -> a different name, so `activate` drops the old cache and `install` repopulates the
 * new one atomically.
 */
function deriveCacheName(shell, digests) {
  const parts = [];
  for (const entry of shell) {
    const key = entry.replace(/^\.\//, '');
    parts.push(key + ':' + String((digests || {})[entry] || digests?.[key] || ''));
  }
  // FNV-1a, 32-bit, hex. Small and dependency-free, which is all a cache key needs.
  // It is NOT collision-free: a collision means a changed asset set reuses the old
  // cache name, so `activate` keeps it and `addAll` overwrites the entries still in the
  // shell. An asset REMOVED from SHELL would survive as a stale cached entry under that
  // collision. That needs a deliberate preimage against this exact shell, so the risk is
  // low — but it is a real limit, not an impossibility, and do not describe it as one.
  let h = 0x811c9dc5;
  const s = parts.join('|');
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = (h + ((h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24))) >>> 0;
  }
  return 'cogitator-' + h.toString(16).padStart(8, '0');
}

const CACHE = deriveCacheName(SHELL, ASSET_DIGESTS);

/** Is this request a document navigation? Only these may be answered with the shell. */
function isNavigation(request) {
  return request.mode === 'navigate' || request.destination === 'document';
}

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  try {
    const url = new URL(e.request.url);
    if (url.origin !== location.origin) return;
  } catch (_) { return; }
  e.respondWith(
    caches.match(e.request, {ignoreSearch: true}).then(hit => hit || fetch(e.request).then(res => {
      // Never cache an error response: a cached 404/500 body replayed from cache later is
      // the same dead-app-with-no-error failure as the HTML fallback above, one layer down.
      if (res && res.ok) {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
      }
      return res;
    }).catch(err => {
      // Offline. ONLY a navigation may fall back to the cached shell. Anything else —
      // a script, a stylesheet, an image — rejects, so the browser reports a real network
      // error against the request that actually failed instead of handing a script the
      // HTML document (CR-0018).
      if (!isNavigation(e.request)) throw err;
      return caches.match('./index.html').then(fallback => {
        // `respondWith(undefined)` is itself a TypeError in the browser; reject cleanly
        // so a navigation with nothing cached surfaces as a failed load, not a crash.
        if (!fallback) throw err;
        return fallback;
      });
    }))
  );
});