#!/usr/bin/env python3
"""Emit the frontend's git read-only policy FROM bridge.py, so there is one source.

CR-Nanites-harness-0009 is the structural cause of CR-Nanites-harness-0001: the bridge's
GIT_READ and the frontend's FRONT_GIT_READ were two hand-maintained copies that had
already drifted, and each layer independently decided `git log` was a read. A fix applied
to one copy leaves the other wrong.

This generator imports bridge.py and writes the JS block that index.html consumes, so the
frontend cannot hold a policy the bridge does not enforce. `tests/frontend/phase16_git_
policy.test.js` asserts the rendered policy, and `test_e2e.py` asserts this generator is
byte-identical to what is committed — so a bridge-side edit that is not regenerated fails
the suite rather than drifting silently.

Usage:
    python3 tools/gen_git_policy.py            # print the block
    python3 tools/gen_git_policy.py --check    # exit 1 if index.html is out of date
"""
import os
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE)

import bridge  # noqa: E402  (needs BASE on sys.path first)

#: The markers index.html wraps the generated block in. Both halves of the contract
#: quote these, so a rename breaks the phase-16 suite loudly instead of silently
#: leaving a stale hand-written copy in place.
BEGIN = "/* ==== BEGIN GENERATED git policy (tools/gen_git_policy.py) ==== */"
END = "/* ==== END GENERATED git policy ==== */"


def render():
    """The JS block, derived from bridge.py's tables. One source, two consumers."""
    read = sorted(bridge.GIT_READ)
    refused = sorted(bridge.GIT_REFUSED_WRITE)
    jailflags = list(bridge.GIT_JAIL_FLAGS)
    return "\n".join([
        BEGIN,
        "/* GENERATED by tools/gen_git_policy.py from bridge.py -- do not edit by hand.",
        "   CR-Nanites-harness-0009: this block and the bridge's tables are the same",
        "   policy. `python3 tools/gen_git_policy.py --check` fails if they drift. */",
        "const FRONT_GIT_READ=new Set(%r);" % (read,),
        "const FRONT_GIT_REFUSED_WRITE=new Set(%r);" % (refused,),
        "const FRONT_GIT_JAIL_FLAGS=%r;" % (jailflags,),
        END,
    ])


def main():
    block = render()
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        path = os.path.join(BASE, "index.html")
        with open(path, encoding="utf-8") as fh:
            html = fh.read()
        if block not in html:
            print("FAIL: index.html's generated git policy is stale.")
            print("      run: python3 tools/gen_git_policy.py --write")
            return 1
        print("ok: index.html's git policy matches bridge.py")
        return 0
    if len(sys.argv) > 1 and sys.argv[1] == "--write":
        path = os.path.join(BASE, "index.html")
        with open(path, encoding="utf-8") as fh:
            html = fh.read()
        start = html.find(BEGIN)
        end = html.find(END)
        if start == -1 or end == -1:
            print("FAIL: markers not found in index.html", file=sys.stderr)
            return 1
        end += len(END)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(html[:start] + block + html[end:])
        print("wrote the generated git policy into index.html")
        return 0
    print(block)
    return 0


if __name__ == "__main__":
    sys.exit(main())
