#!/usr/bin/env python3
"""Emit sw.js's ASSET_DIGESTS map FROM the real precached asset files.

CR-Nanites-harness-0007: `CACHE` was the hand-maintained literal 'cogitator-v10' and
nothing in the repo bumped it, so once a shell entry was cached it was served forever
(cache-first, no revalidation, no TTL) until a human remembered to edit one line.

The cache name is now DERIVED from the precached assets' contents via
`deriveCacheName()` in sw.js, and the digests it hashes are generated here — so the
cache name changes exactly when an asset changes, and `activate` drops the old cache
atomically.

This mirrors `tools/gen_git_policy.py`, which solves the same class of problem (two
hand-maintained copies drifting) for the git policy: one source, a generated block, and
a `--check` mode that `test_e2e.py` runs — so shipping a changed asset without
regenerating FAILS THE SUITE instead of silently serving a stale cache forever.

`./sw.js` is deliberately excluded from the digest set: this file embeds the digests, so
hashing sw.js's own bytes is a self-reference whose fixed point does not exist.

The exclusion is sound, but the reason is NOT "sw.js's content is determined by the
other digests" — that is false, since sw.js also holds the fetch handler, isNavigation
and deriveCacheName, and editing any of those changes sw.js without changing any asset.
The real reason is narrower: the cache name only needs to track ASSET content. A
handler-only edit changes no precached asset, and a service-worker update is driven by
the script's own bytes rather than by CACHE, so it correctly needs no cache bump.
This does NOT mean every sw.js edit bumps the cache.

Usage:
    python3 tools/gen_sw_cache.py            # print the block
    python3 tools/gen_sw_cache.py --check    # exit 1 if sw.js is out of date
    python3 tools/gen_sw_cache.py --write    # rewrite the block in sw.js
"""
import hashlib
import os
import re
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#: The markers sw.js wraps the generated block in. The phase-21 suite quotes these too,
#: so a rename breaks loudly instead of leaving a stale hand-written copy in place.
BEGIN = "/* ==== BEGIN GENERATED asset digests (tools/gen_sw_cache.py) ==== */"
END = "/* ==== END GENERATED asset digests ==== */"

#: sw.js embeds the digests, so it cannot hash itself. See the module docstring.
SELF = "./sw.js"

SHELL_RE = re.compile(r"^const SHELL\s*=\s*\[(.*?)\];", re.S | re.M)
STRING_RE = re.compile(r"'([^']*)'")


def read_shell():
    """The precached asset list, read from sw.js — the single list both sides share.

    Parsed rather than duplicated so this generator and the service worker can never
    disagree about WHAT is precached: adding an asset to sw.js's SHELL is enough, and
    --check then fails until the digests are regenerated for it.
    """
    with open(os.path.join(BASE, "sw.js"), encoding="utf-8") as fh:
        src = fh.read()
    m = SHELL_RE.search(src)
    if not m:
        raise SystemExit("FAIL: could not find `const SHELL = [...]` in sw.js")
    return STRING_RE.findall(m.group(1))


def digest_of(rel):
    """sha256 of one asset's bytes, hex-truncated. Missing file is an error, never ''.

    A missing file must NOT become an empty digest: an empty digest is exactly the
    'constant cache name' shape CR-0007 describes, so a typo'd asset path would silently
    disable invalidation for that entry instead of failing loudly.
    """
    path = os.path.join(BASE, rel.replace("./", "", 1))
    if not os.path.exists(path):
        raise SystemExit("FAIL: precached asset does not exist: %s" % rel)
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()[:16]


def render(shell):
    lines = [
        BEGIN,
        "/* GENERATED by tools/gen_sw_cache.py from the real asset files -- do not edit by",
        "   hand. `python3 tools/gen_sw_cache.py --check` fails if these do not match, and",
        "   test_e2e.py runs that check. CR-Nanites-harness-0007: this map is what makes",
        "   CACHE a derivation rather than a human-remembered literal. */",
        "const ASSET_DIGESTS = {",
    ]
    for entry in shell:
        if entry == SELF:
            lines.append("  '%s': '' /* excluded: embeds this map */," % entry)
            continue
        lines.append("  '%s': '%s'," % (entry, digest_of(entry)))
    lines.append("};")
    lines.append(END)
    return "\n".join(lines)


def main():
    shell = read_shell()
    block = render(shell)
    path = os.path.join(BASE, "sw.js")

    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        with open(path, encoding="utf-8") as fh:
            src = fh.read()
        if block not in src:
            print("FAIL: sw.js's asset digests are stale w.r.t. the real files.")
            print("      run: python3 tools/gen_sw_cache.py --write")
            return 1
        print("ok: sw.js's asset digests match the real precached files")
        return 0

    if len(sys.argv) > 1 and sys.argv[1] == "--write":
        with open(path, encoding="utf-8") as fh:
            src = fh.read()
        start, end = src.find(BEGIN), src.find(END)
        if start == -1 or end == -1:
            print("FAIL: generated-digest markers not found in sw.js", file=sys.stderr)
            return 1
        end += len(END)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(src[:start] + block + src[end:])
        print("wrote the generated asset digests into sw.js")
        return 0

    print(block)
    return 0


if __name__ == "__main__":
    sys.exit(main())